"""Initial logistics schema

Revision ID: 107cfb399813
Revises: 0745d016dc37
Create Date: 2026-06-26 15:58:11.937159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '107cfb399813'
down_revision: Union[str, Sequence[str], None] = '0745d016dc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('deliveries', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('deliveries', sa.Column('delivery_window_start', sa.DateTime(), nullable=True))
    op.add_column('deliveries', sa.Column('delivery_window_end', sa.DateTime(), nullable=True))
    op.add_column('deliveries', sa.Column('assigned_driver_id', sa.Integer(), nullable=True))
    op.add_column('deliveries', sa.Column('assigned_vehicle_id', sa.Integer(), nullable=True))
    op.add_column('deliveries', sa.Column('route_order', sa.Integer(), nullable=True))
    op.add_column('deliveries', sa.Column('estimated_arrival', sa.DateTime(), nullable=True))
    op.alter_column('deliveries', 'customer_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('deliveries', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('deliveries', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
    op.alter_column('deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('deliveries_warehouse_id_fkey'), 'deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'deliveries', 'drivers', ['assigned_driver_id'], ['id'])
    op.create_foreign_key(None, 'deliveries', 'vehicles', ['assigned_vehicle_id'], ['id'])
    op.drop_column('deliveries', 'time_window_end')
    op.drop_column('deliveries', 'warehouse_id')
    op.drop_column('deliveries', 'weight_kg')
    op.drop_column('deliveries', 'time_window_start')
    op.drop_column('deliveries', 'updated_at')
    op.add_column('drivers', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('shift_start', sa.DateTime(), nullable=True))
    op.add_column('drivers', sa.Column('shift_end', sa.DateTime(), nullable=True))
    op.add_column('drivers', sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('current_longitude', sa.Float(), nullable=True))
    op.alter_column('drivers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('drivers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('drivers', 'license_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
    op.drop_constraint(op.f('drivers_license_number_key'), 'drivers', type_='unique')
    op.drop_constraint(op.f('drivers_phone_key'), 'drivers', type_='unique')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_column('drivers', 'updated_at')
    op.drop_column('drivers', 'created_at')
    op.add_column('vehicles', sa.Column('capacity_weight', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('capacity_volume', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(length=30), nullable=True))
    op.add_column('vehicles', sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('current_longitude', sa.Float(), nullable=True))
    op.alter_column('vehicles', 'vehicle_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=True)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_column('vehicles', 'capacity_kg')
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('capacity_kg', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.alter_column('vehicles', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('vehicles', 'vehicle_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('vehicles', 'current_longitude')
    op.drop_column('vehicles', 'current_latitude')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'capacity_volume')
    op.drop_column('vehicles', 'capacity_weight')
    op.add_column('drivers', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_unique_constraint(op.f('drivers_phone_key'), 'drivers', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('drivers_license_number_key'), 'drivers', ['license_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('drivers', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('drivers', 'license_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('drivers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('drivers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('drivers', 'current_longitude')
    op.drop_column('drivers', 'current_latitude')
    op.drop_column('drivers', 'shift_end')
    op.drop_column('drivers', 'shift_start')
    op.drop_column('drivers', 'rating')
    op.add_column('deliveries', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('time_window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('weight_kg', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('time_window_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('deliveries_warehouse_id_fkey'), 'deliveries', 'warehouses', ['warehouse_id'], ['id'])
    op.alter_column('deliveries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('deliveries', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('deliveries', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('deliveries', 'customer_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('deliveries', 'estimated_arrival')
    op.drop_column('deliveries', 'route_order')
    op.drop_column('deliveries', 'assigned_vehicle_id')
    op.drop_column('deliveries', 'assigned_driver_id')
    op.drop_column('deliveries', 'delivery_window_end')
    op.drop_column('deliveries', 'delivery_window_start')
    op.drop_column('deliveries', 'volume')
    op.drop_column('deliveries', 'weight')
    # ### end Alembic commands ###
