"""add vehicle location timestamp

Revision ID: 975702ec749e
Revises: c15fde3f4916
Create Date: 2026-08-19 15:20:17.815027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975702ec749e'
down_revision: Union[str, Sequence[str], None] = 'c15fde3f4916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('vehicles', 'vehicle_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'vehicle_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('vehicles', 'last_location_update')
    # ### end Alembic commands ###
