"""create route stops table

Revision ID: ca71401beaa2
Revises: f55551988ad4
Create Date: 2026-06-14 16:55:08.978647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca71401beaa2'
down_revision: Union[str, Sequence[str], None] = 'f55551988ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('planned_arrival_time', sa.DateTime(), nullable=False),
    sa.Column('actual_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('planned_departure_time', sa.DateTime(), nullable=False),
    sa.Column('actual_departure_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_id'), 'route_stops', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stops_id'), table_name='route_stops')
    op.drop_table('route_stops')
    # ### end Alembic commands ###
